
#기본 설정
server:
  port: 8081
  
logging.level:
  org.springframework:
    security: debug
    boot: info

---
#local 설정
server:
  port: 8081
  
security:
  oauth2:
    client:
      client-id: rest_server_id
      client-secret: rest_server_secret
    resource:
      jwt.key-uri: http://localhost:8080/oauth/token_key
    
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/oauth
    driver-class-name: org.mariadb.jdbc.Driver
    username: oauth
    password: oauth@123    
    
---
#dev 설정
server:
  port: 8081
  
spring:
  profiles: dev
  
---
#product 설정
server:
  port: 8081
  
spring:
  profiles: prod