server:
  port: 8081
  
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
      
# 외부 DB 설정시 아래의 주석을 활성화 시킨 후 관련 DB 설정 정보를 입력한다.
spring:
 datasource:
   url: jdbc:oracle:thin:@112.169.9.236:1521:orcl
   driverClassName: oracle.jdbc.driver.OracleDriver
   username: cenworks_suite
   password: cenworks_suite

security:
  oauth2:
    client:
      client-id: foo
      client-secret: bar
    resource:
      jwt.key-uri: http://localhost:8080/oauth/token_key
      
logging.level:
  org.springframework:
    security: debug
    boot: debug
    